language: bash
sudo: required

env:
  global:
    - ARDUINO_VERSION=1.8.12
    - ARDUINO_FILE=arduino-${ARDUINO_VERSION}-linux64.tar.xz

before_install:
  - sudo apt-get update
  - sudo apt-get install -y fakeroot debhelper devscripts libsecret-1.0

install:
  - dpkg-buildpackage -uc -us
  - sudo dpkg -i ../arduino-package*.deb

script:
  - wget http://downloads.arduino.cc/${ARDUINO_FILE}
  - make-arduinopkg ${ARDUINO_FILE}

notifications:
  email:
    on_success: change
    on_failure: change
